# -*- coding: utf-8 -*-
"""curso basico python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a96fIvXZ1UD1KGhNcR3G5RlAl9ylaI-p

Passo a passo de solução do desafio
"""

#@title Default title text
# Logica de programação
#passo 0 - Entender o desafio 
#passo 1 - percorrer todos os arquivos da pasta base de dados
import os
import pandas as pd



lista_arquivo = os.listdir("/content/drive/MyDrive/Curso Python/Vendas")
display(lista_arquivo)

tabela_total = pd.DataFrame()

#passo 2 - importar as bassse de dados de vendas
for arquivo in lista_arquivo:
  #se tem a palavra "Vendas" o nome do arquivo
  if "Vendas" in arquivo:
    # importar o arquivo
    tabela = pd.read_csv(f"/content/drive/MyDrive/Curso Python/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela)

#passo 3 - tratar /compilar as bases de dados
display(tabela_total)

#passo 4 - calcular o produto mais vendido
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida",ascending = False)
display(tabela_produtos)

#passo 5 - calcular o produto que mais faturou
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida']  * tabela_total['Preco Unitario']
tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento",ascending = False)
display(tabela_faturamento)

#passo 6 - calcular loja/cidade que mais vendeu (em faturamento)
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']]
display(tabela_lojas)

# passo 7  criar um grafico/dashbord
import plotly.express as px

grafico = px.bar(tabela_lojas, x=tabela_lojas.index , y='Faturamento')
grafico.show()